#auto: true
#server: true
#markdown: kramdown
remote_theme: samarsault/plainwhite-jekyll

title: futabato.github.io
author: futabato
email: 01futabato10@gmail.com

plainwhite:
  name: futabato
  date_format: "%b %-d, %Y"
  #sitemap: true
  #search: true
  dark_mode: true
  portfolio_image: "assets/icon.jpg"
  html_lang: "ja"

  # generate social links in footer
  social_links:
    twitter: 01futabato10
    github:  futabato
    #linkedIn: 
    #rss: rss
    #dribbble: jekyll
    #flickr:   jekyll
    #instagram: jekyll
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    #soundcloud: jekyll
    #telegram: jekyll
    #gitlab: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme