#auto: true
server: true
markdown: kramdown
remote_theme: samarsault/plainwhite-jekyll

title: futabato.github.io
author: futabato
email: 01futabato10@gmail.com

plainwhite:
  name: futabato
  tagline: Nice to meet you.
  date_format: "%b %-d, %Y"
  #sitemap: true
  #search: true
  dark_mode: true
  portfolio_image: "assets/icon.jpg"
  html_lang: "ja"

  # generate social links in footer
  social_links:
    twitter: 01futabato10
    github:  futabato

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - about.md

sass: 
  sass_dir: _sass 
  style: :compressed

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-feed